implemented smoke tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,15 +21,7 @@ commands:
             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_ID >>
             aws s3 rm s3://udapeople-<<parameters.workflow_ID>> --recursive
             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_ID >>
-  install-dependencies:
-    description: install Node.js & tar and curl
-    steps:
-      - run:
-          name: install Node.js & tar and curl
-          command: |
-            yum install -y tar gzip curl
-            curl -fsSL https://rpm.nodesource.com/setup_13.x | bash -
-            yum -y install nodejs
+
 orbs:
   slack: circleci/slack@4.12.0
 
@@ -214,7 +206,7 @@ jobs:
       - run:
           name: Send migration results to kvdb
           command: |
-            if grep -q "has been executed successfully." ./backend/migrations_dump.txt
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
               curl --insecure https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
@@ -225,10 +217,14 @@ jobs:
       - image: amazon/aws-cli
     steps:
       - checkout
-      - install-dependencies
       - restore_cache:
           keys: [frontend-build]
-
+      - run:
+          name: install Node.js & tar and curl
+          command: |
+            yum install -y tar gzip curl
+            curl -fsSL https://rpm.nodesource.com/setup_13.x | bash -
+            yum -y install nodejs
       - run:
           name: Get backend url
           command: |
@@ -280,6 +276,49 @@ jobs:
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
       - destroy-environment
+
+  smoke-test:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt update -y
+            sudo apt install awscli -y
+      - run:
+          name: Get backend url
+          command: |
+            BACKEND_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo "${API_URL}" > backend_ip.txt
+
+      - run:
+          name: Backend smoke test.
+          command: |
+            if curl ${API_URL}/api/status | grep "ok"
+            then
+                return 0
+            else
+                exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+            echo ${URL}
+            if curl -s ${URL} | grep "Welcome"
+            then
+                return 1
+            else
+                return 1
+            fi
+      # Here's where you will add some code to rollback on failure
 
 workflows:
   default:
